#!/usr/bin/env bash

set -ex

mv .resources _resources

echo "Updating files with template..."

files="index.html examples/examples.html examples/examples-2.html"

python _resources/retemplate.py $files
for file in $files ; do
    sed -i '' 's/\.resources/_resources/g' $file
done
