#!/usr/bin/env bash

set -e

cd "$(dirname $BASH_SOURCE)"

echo "Updating files with template..."
python retemplate.py ../license.html ../index.html ../examples.html

rm -rf _build
mkdir _build
mkdir _build/.resources
echo -n "Copying/staging..."
cp ../*.html ../*.css ../*.js _build/
cp *.js *.css _build/.resources/
echo "done."

if [ "$1" != "-n" ] ; then
    echo "Pushing..."
    ghp-import -p -m "auto update" _build
fi
