#!/usr/bin/env bash

set -ex

echo `pwd`
ls -l .resources
mv .resources resources
ls -l resources

echo "Updating files with template..."

files="index.html examples/examples.html examples/examples-2.html"

python resources/retemplate.py $files
for file in $files ; do
    sed -i '' 's/\.resources/resources/g' $file
done

ls -l resources

mv resources/CNAME CNAME
